version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "4000:4000"
#    volumes:
#      - "/Users/rodri/Desktop/projects/react-boilerplate/build"
