name: BOILERPLATE
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  tests:
    runs-on: ubunto-latest
    steps:
      - name: test
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@2.2.0
      - name: Install dependencies
        run: yarn install
      - name: Test and coverage
        run: yarn coverage
